[package]
name = "torchtest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tch = "0.16.0"
anyhow = "1.0.86"
rand = "0.8.5"
kdam = "0.5.2"
num-traits = "0.2.19"
